dist: bionic
os:
- linux
language: python
python:
- '3.7'
env:
  global:
    - secure: ZQsKjX/hARPuRloFyxaUD9RAEi4dcTmW0nsShWY6YvQVyU8gnH5xXNUWNFgnWe+JeXu7/fWmIoeupzE3Otc6FjBI4SFod4uzYMRNaUNd0eO6cCA+Dw/hXKb4ekqkLFmjQXxW8vY3HbnUE/kLW0XX/w08h15vlKQiaQBAPEeFKy8s8O6/EYPXqW7HERvCPWIO3Xm4mGmpqV/o7jNrk8V3P6t1iotnEC4PDFTfOxJRQlRNvlWkaIkMA57fBRPg4BJXSATSu1I7hEsIB0Zup7AiLbXwKXhlHGXK1Ll/NNDgTERUxHTSXPLRw23pdP2GiSY8PNqrTCa95NaXaYkbEw68dqzHz0YD0GssMqiL2bWoR/3VhbjZmuDelvYinwjNHNyOWHvQZwbWzPmh5Pj4Y+43j4LqfOB/Y+Phsp+GVxV/n4HYJ/l++7Xg/ekugE/loTq7CnrWqGdH3w0+Ti7DRwxUYBYRfhN8/tilD83A1bkNqFagcHFr8d4XrdcvIrB/U17t+ZRMsHUK/xWH1/dMohUIiHdBGGyye9ZUp6M/ddEwrf9Cdk+xBFyzi9p3qVVUq/5NqSDcCZr7Dbnawg+fY3E5bqoSIiJzU1KW6h7zdaRzbBzdetbH5ALhAwmuIwsUz4v3YIyKqDGmeridr5zzY1B8ZbZiFzp8pOPDYeUPX2zVbeA=
addons:
  apt:
    packages:
    - python3.7
    - python3-pip
    - git
install:
- pip3 install -r requirements.txt
  # Try a stable version instead.
  # - git clone https://github.com/xingweitian/mkdocs-rtd-dropdown.git && cd mkdocs-rtd-dropdown
  # && python3 setup.py install && cd ..
script:
- git clean -f -d -x
after_success:
- ./deploy-to-gh-pages.sh


