site_name: VidarDB
theme:
    name: 'rtd-dropdown'
repo_url: https://github.com/vidardb/docs
site_author: VidarDB Team
copyright: 2020 VidarDB Inc. All Rights Reserved.
nav:
    - 'Welcome to VidarDB': 'index.md'
    - 'What is VidarDB': 'what_is_vidarDB.md'
    - 'Run VidarDB with Docker': 'run_vidarDB_with_docker.md'
    - 'VidarDB 101': 'vidarDB_101.md'
    - 'VidarDB Examples': 'example.md'
    - 'Run KMeans with VidarDB': 'run_kmeans_with_vidarDB.md'
    - 'Frequently Asked Questions': 'faq.md'
