site_name: VidarDB
theme:
    name: 'rtd-dropdown'
repo_url: https://github.com/vidardb/docs
site_author: VidarDB Team
copyright: 2020 VidarDB Inc. All Rights Reserved.
nav:
    - 'Welcome to VidarDB': 'index.md'
    - 'Quick Start with Docker': 'quick_start_with_docker.md'
